name: Entry project
services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../src:/project/src"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./local-setup/postgres/:/var/lib/postgresql/data/"
